# Generated by Django 4.2.17 on 2025-01-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='description',
        ),
        migrations.RemoveField(
            model_name='level',
            name='name',
        ),
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
