# Generated by Django 4.2.17 on 2025-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_level_description_remove_level_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
