# Generated by Django 4.2.17 on 2024-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('science', 'Наука'), ('art', 'Искусство'), ('health', 'Медицина'), ('sport', 'Спорт'), ('it', 'IT'), ('business', 'Бизнес')], default='science', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_task',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
