# Generated by Django 4.2.17 on 2025-01-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('mental', 'Ментальный'), ('physical', 'Физический')], default='mental', editable=False, max_length=10),
        ),
    ]
