# Generated by Django 4.2.17 on 2024-12-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_category_alter_userprofile_current_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
