# Generated by Django 4.2.17 on 2025-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_level_level_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_task',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_task_number',
            field=models.IntegerField(default=1),
        ),
    ]
