# Generated by Django 4.2.17 on 2024-12-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_level_remove_task_is_completed_remove_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('mental', 'Ментальная'), ('physical', 'Физическая')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
