# Generated by Django 4.2.17 on 2024-12-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_task_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
        migrations.AddField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('mental', 'Ментальный'), ('physical', 'Физический')], default='mental', max_length=10),
        ),
    ]
